version: '3'

services:
  backend:
    image: 'medibank-digital'
    environment:
      UNSPLASH_ACCESS_KEY: 'your_key'
    expose:
      - '8080'
    ports:
      - '8080:8080'
  frontend:
    image: 'medibankdigital/hacker-card-frontend:latest'
    depends_on:
      - backend
    expose:
      - '3001'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    ports:
      - '4000:4000'